### ISSUE TITLE
Race condition causing failed initial parameterization store

### ISSUE THREAD

**Issue by tgvaughan** [tgvaughan/BDMM-Prime#1]
```
Fatal exception: null
java.lang.NullPointerException
	at bdmmprime.parameterization.Parameterization.store(Parameterization.java:302)
	at beast.core.State.storeCalculationNodes(State.java:294)
	at beast.core.MCMC.run(MCMC.java:302)
	at beast.app.BeastMCMC.run(BeastMCMC.java:357)
	at beast.app.beastapp.BeastMain.<init>(BeastMain.java:113)
	at beast.app.beastapp.BeastMain.main(BeastMain.java:659)
Fatal exception: null
java.lang.RuntimeException: An error was encounted. Terminating BEAST
	at beast.app.util.ErrorLogHandler.publish(ErrorLogHandler.java:30)
	at java.util.logging.Logger.log(Logger.java:738)
	at java.util.logging.Logger.doLog(Logger.java:765)
	at java.util.logging.Logger.log(Logger.java:788)
	at java.util.logging.Logger.severe(Logger.java:1464)
	at beast.app.beastapp.BeastMain.<init>(BeastMain.java:177)
	at beast.app.beastapp.BeastMain.main(BeastMain.java:659)
```

**Comment by tgvaughan** [comment]
This no longer occurs.
